---
- name: Jenkins
  hosts: all
  become: yes
  gather_facts: no
  vars:
    user: cinarra
  tasks:
    - name: Wait for system to boot up
      local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=300
      become: False
    - setup:

    - name: switch off selinux
      selinux:
        state: disabled

    - name: create user Cinarra
      user:
        name: "{{ user }}"
        shell: /bin/bash
        state: present
        ssh_key_type: rsa
        generate_ssh_key: yes
        expires: -1
        groups: wheel
        append: yes

    - name: Set pub keys
      authorized_key:
        user: "{{ user }}"
        key: '{{ item }}'
      with_file:
        - '~/.ssh/id_rsa.pub'

    - name: Add sudo rule
      copy:
        content: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/95-m-{{ user }}-users"
        force: no

    - name: copy repo file
      copy:
        src: "./templates/{{ item }}"
        dest: /etc/yum.repos.d/
      with_items:
        - nginx.repo

    - name: get jenkins repo 
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: 0644
    - name: ... and rpm key
      rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: I don't know exactly order in a <with_item> operator, so I'll be install java at first
      yum:
        name: java-1.8.*-openjdk-devel
        state: present

    - name: nginx and jenkins
      yum:
        name: ['nginx', 'jenkins']
        state: present

    - name: Copy nginx config
      copy:
        src: jenkins.conf
        dest: /etc/nginx/conf.d/
        mode: 0644

    - name: Start service nginx and jenkins
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - jenkins
        - nginx